import { agentArchivePath, DEFAULT_EXECUTION_LIMITS } from "../config.js";
import { record, string } from "../core.js";
import { setupConfiguration, type FileChange } from "./install.js";

function cell(value: string): string { return value.replaceAll("|", "\\|").replace(/\r?\n/g, " "); }
function block(content: string): string {
  const length = Math.max(3, ...(content.match(/`+/g) ?? []).map((run) => run.length + 1));
  const fence = "`".repeat(length);
  return `${fence}markdown\n${content}\n${fence}`;
}

export function setupReportPath(output: string): string {
  return /\.json$/i.test(output) ? output.replace(/\.json$/i, ".md") : `${output}.md`;
}
export function describeInstallationFile(change: FileChange): FileChange & { ownership: string; purpose: string } {
  const path = change.path;
  const workflowPurposes: Record<string, string> = {
    "crewbie-plan.yml": "Prepare a coordinator plan from approved issue intake; the planning opt-in gate still applies.",
    "crewbie-execute-plan.yml": "Verify exact-head human approval and merge before publishing implementation tasks.",
    "crewbie-dispatch.yml": "Release approved tasks when dependencies, capacity and launch controls permit; mark finished PRs ready, request reviews, continue on address-review and auto-merge in auto mode.",
    "crewbie-review.yml": "Have the configured Crewbie reviewer comment on each finished PR head; reads the API diff and never runs PR code.",
    "crewbie-maintain.yml": "Offer bounded knowledge-maintenance proposals; scheduled analysis remains opt-in.",
    "crewbie-report.yml": "Collect execution evidence into a static report without starting implementation agents.",
  };
  const detail = change.after === null ? ["Archived original", "Remove the original only after preserving its approved charter in the agent archive."]
    : path === ".crewbie/config.json" ? ["User policy", "Team, explicit models, approvals and limits; update preserves your configuration."]
    : path === ".crewbie/managed.json" ? ["Crewbie bookkeeping", "Fingerprints protect human edits during updates; do not reset to bypass conflicts."]
    : path.startsWith(".crewbie/agent-archive/") ? ["Preserved original", "Keep the adopted agent's original domain guidance and restrictions."]
    : path.startsWith(".crewbie/team/") ? ["User knowledge", path.endsWith("/index.md")
      ? "Seed topic pointers for selective context loading; existing knowledge is never regenerated."
      : "Seed current role handoffs and lessons once; existing knowledge is never regenerated by update."]
    : /(?:constitution|decisions)\.md$/.test(path) ? ["User guidance", "Keep approved principles or shared decisions; reuse existing documents."]
    : path.startsWith(".github/agents/crewbie-") ? ["Crewbie-managed", "The specialist charter links shared rules and scoped memory; edited files block update."]
    : path.startsWith(".github/workflows/crewbie-") ? ["Crewbie-managed", `${workflowPurposes[path.slice(".github/workflows/".length)] ?? "Run the named Crewbie operation with bounded permissions."} Human-edited workflows block update.`]
    : path === ".github/skills/crewbie/SKILL.md" ? ["Crewbie-managed", "Discover the local implementation workflow on demand instead of always loading it."]
    : path === ".crewbie/instructions.md" ? ["Crewbie-managed", "Single shared working policy referenced by specialists, not duplicated into each charter."]
    : /pull_request_template/i.test(path) ? ["Crewbie-managed", "Prompt for concise implementation evidence, handoffs and learning."]
    : ["Reviewed guidance", "Apply only the separately approved instruction replacement; preserve subsequent edits."];
  return { ...change, ownership: detail[0]!, purpose: detail[1]! };
}
function filePreview(change: FileChange): string {
  const detail = describeInstallationFile(change);
  return `${change.after === null ? "Archive/remove" : change.before === null ? "Create" : "Update"} ${change.path} [${detail.ownership}] - ${detail.purpose}`;
}

export function renderSetupMarkdown(value: unknown, changes?: FileChange[]): string {
  const data = record(value, "setup proposal");
  const config = setupConfiguration(data);
  const review = data.review === undefined ? undefined : record(data.review, "setup review");
  const installed = new Set(Array.isArray(data.installedRoles) ? data.installedRoles.map((role) => string(record(role, "installed role").id, "installed role id")) : []);
  const instructions = Array.isArray(data.instructions) ? data.instructions.map((raw) => record(raw, "guidance edit")) : [];
  const lines = [
    "# Crewbie assessment", "",
    review ? string(review.summary, "assessment summary") : "Reviewed setup proposal.", "",
    "## Proposed crew", "",
    "| Specialist | Action | Model | Responsibility |", "| --- | --- | --- | --- |",
    ...config.roles.map((role) => `| ${cell(role.id)} | ${installed.has(role.id) ? "Keep/update installed specialist" : role.sourceAgent ? `Adopt ${cell(role.sourceAgent)}` : "New specialist"} | ${cell(role.model)} | ${cell(role.purpose)} |`),
    "", `Concurrency: ${config.maxActive} active sessions. This is not a limit on team size.`, "",
    `Model profile: **${config.modelProfile ?? "balanced"}**. Explicit model overrides remain authoritative.`,
    `Crewbie launch limits: **${(config.execution ?? DEFAULT_EXECUTION_LIMITS).maxLaunchesPerBatch} per batch / ${(config.execution ?? DEFAULT_EXECUTION_LIMITS).maxAttemptsPerTask} per task**, including the first attempt and uncertain requests. Not a monetary cap.`, "",
  ];
  for (const role of config.roles) {
    lines.push(`### ${role.id}`, "");
    if (role.sourceAgent) lines.push(`Original: \`${role.sourceAgent}\` -> \`.github/agents/crewbie-${role.id}.agent.md\`.`,
      `Archive: \`${agentArchivePath(role.sourceAgent)}\` (backup provenance). The active charter contains the complete original instructions, with tool restrictions and persona preserved; only lines that just point to guidance Copilot loads automatically are left out.`, "");
    if (role.checks?.length) lines.push("**Checks**", ...role.checks.map((check) => `- ${check}`), "");
    if (role.modelReason) lines.push(`**Model proposal (${role.complexity ?? "unclassified"}):** ${role.modelReason}`, "");
    if (role.nonNegotiables?.length) lines.push("**Boundaries**", ...role.nonNegotiables.map((rule) => `- ${rule}`), "");
  }
  if (review && Array.isArray(review.agentDecisions) && review.agentDecisions.length) {
    lines.push("## Existing agent decisions", "");
    for (const raw of review.agentDecisions) {
      const decision = record(raw, "agent decision");
      lines.push(`- **${string(decision.action, "agent action")} \`${string(decision.path, "agent path")}\`**: ${string(decision.reason, "agent reason")}`);
    }
    lines.push("");
  }
  lines.push("## Proposed guidance edits", "",
    instructions.length ? `${instructions.length} concrete edits. These are applied only when guidance changes are approved.`
      : "**No existing guidance edits proposed.** Recommendations below are advisory; choosing to apply guidance does not turn recommendations into file edits.", "");
  for (const instruction of instructions) lines.push(`### ${string(instruction.path, "guidance path")}`, "",
    typeof instruction.reason === "string" ? instruction.reason : "Reviewed replacement text.", "",
    block(string(instruction.content, "guidance content")), "");
  if (typeof data.constitutionText === "string") lines.push("### Proposed constitution", "", block(data.constitutionText), "");
  lines.push("## Hosted planning", "", config.planning?.enabled
    ? `Enabled with model \`${config.planning.model}\`. The ready-for-planning label authorizes a potentially billable planning run. Execution after exact-head human approval and merge: **${config.planning.executeOnMerge ? "enabled (paid work authorized by that approval and merge)" : "disabled (manual execution approval required)"}**.`
    : "**Disabled.** The ready-for-planning label will not create a plan. Dispatch only handles published, approved implementation tasks.", "");
  if (review && Array.isArray(review.findings)) {
    lines.push("## Assessment findings and recommendations", "", "Recommendations are not automatically applied. Only the concrete guidance edits above are proposed writes.", "");
    for (const raw of review.findings) {
      const finding = record(raw, "assessment finding");
      lines.push(`### ${string(finding.area, "finding area")}${typeof finding.path === "string" ? ` - ${finding.path}` : ""}`, "",
        string(finding.assessment, "finding assessment"), "", `**Recommendation:** ${string(finding.recommendation, "finding recommendation")}`, "",
        ...(typeof finding.action === "string" ? [`**Disposition:** ${finding.action}`, ""] : []),
        ...(typeof finding.deferReason === "string" ? [`**Deferred because:** ${finding.deferReason}`, ""] : []));
    }
  }
  if (data.inventory !== undefined) {
    const inventory = record(data.inventory, "inventory");
    lines.push("## Coverage", "", string(inventory.scope, "inventory scope"), "");
    if (Array.isArray(inventory.omitted)) for (const raw of inventory.omitted) {
      const item = record(raw, "omitted file");
      lines.push(`- \`${string(item.path, "omitted path")}\`: ${string(item.reason, "omission reason")}`);
    }
  }
  if (Array.isArray(data.questions) && data.questions.length) lines.push("", "## Open questions", "", ...data.questions.map((question) => `- ${string(question, "question")}`));
  if (changes) lines.push("", "## Reviewed installation files", "", ...changes.map((change) => `- ${filePreview(change)}`));
  return lines.join("\n") + "\n";
}

export function renderInstallationPreview(changes: FileChange[], labels: readonly string[], repository: string): string {
  return [
    `\nInstallation preview: ${changes.length} files`, "",
    ...[
      { label: "CREATE", files: changes.filter((change) => change.before === null) },
      { label: "UPDATE", files: changes.filter((change) => change.before !== null && change.after !== null) },
      { label: "ARCHIVE / REMOVE ORIGINAL", files: changes.filter((change) => change.after === null) },
    ].flatMap((group) => group.files.length ? [
      `${group.label} | ${group.files.length} files`,
      ...group.files.map((change) => {
        const detail = describeInstallationFile(change);
        return `  ${change.path}\n    ${detail.ownership}: ${detail.purpose}`;
      }), "",
    ] : []),
    labels.length ? `GITHUB LABELS | ${labels.length} in ${repository || "(repository not set)"}\n${labels.map((label) => `  ${label}`).join("\n")}` : "GitHub labels skipped.",
    "", "Preview only. Nothing above is applied until confirmed.",
  ].join("\n");
}
